### ISSUE TITLE
Pray Watch Beta Feedback? 

### ISSUE THREAD

**Issue by quantumgolem** [basememara/PrayKit#1]
I apologize for this might be a little irrelevant, but I have not gotten any response from contacting Zamzam via email. Where do we give feedback for the TestFlight beta version of Pray Watch?

**Comment by basememara** [comment]
Salam, the best way is to contact us thru the TestFlight app or the feedback button within the app. We are trying to catch up with the responses. The GitHub is mostly for developers, so you can still post an issue or suggestion here but it would be great to contribute and create a pull request which is what the main goal of open-sourcing PrayKit was.
